# **Task 3**

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
from pyspark.sql import SparkSession

SEED = 42

# Increased memory to handle the dataset size and cross-validation overhead
spark = (
    SparkSession.builder
    .appName("Task3_ML_Portfolio")
    .config("spark.driver.memory", "8g")
    .config("spark.executor.memory", "4g")
    .config("spark.sql.shuffle.partitions", "8")
    .getOrCreate()
)

print("Spark Version:", spark.version)
print("Spark Session initialized with 8GB Driver Memory.")

Spark Version: 4.0.3
Spark Session initialized with 8GB Driver Memory.

In [3]:
processed_df = spark.read.parquet(
    "/content/drive/MyDrive/7006SCN/processed_reviews"
)

In [4]:
processed_df.printSchema()

root
 |-- rating: double (nullable = true)
 |-- text: string (nullable = true)
 |-- title: string (nullable = true)
 |-- review: string (nullable = true)
 |-- label: double (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- filtered_words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- rawFeatures: vector (nullable = true)
 |-- features: vector (nullable = true)

In [5]:
processed_df.select(
    "label",
    "features"
).show(5, truncate=False)

+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|label|features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|2.0  |(10000,[36,274,288,815,1092,1790,1818,2096,2335,2589,2610,2962,3055,3330,3365,3372,3423,3761,3943,4084,4112,4315,4331,4623,4818,5014,5734,6198,6218,6287,6470,6600,6799,7569,7611,7642,7924,7939,8166,8191,8449,8527,8565,8591,8742,9126,9160,9348,9669,9851],[13.220731494832055,4.852348200204124,3.487294051485435,1.9489085834193474,7.5708276976033195,6.652167444794066,5.931987587735763,8.097015165048328,3.0291213416230343,3.5731450347986207,12.042416560760259,19.89189433462683,8.023808081241325,3.0157736124830774,4.083773278780595,3.8143288942488853,3.625962841569335,5.024980220462653,5.315723142842269,6.0967661967673115,2.027968335988488,6.929398349751884,6.809494422526363,10.333440179649342,4.007904711795436,11.69439483528713,5.396717677566673,4.67487120498637,8.573396937251452,3.3263150298635127,10.024826588318287,5.009434012201732,6.9188385895368825,3.3338035274012356,13.981373347446333,5.329346171746872,6.82276475944726,5.599326160478641,3.653095215847555,5.75976646441977,5.641763720973861,5.537810170022278,6.9974817168559955,6.595051512442985,3.994615857029904,4.0990616257770025,7.765106530375566,5.611755699030744,9.041205175933753,7.102842232513821])|
|0.0  |(10000,[447,625,1929,3055,3372,3793,6207,6581,6683,7403,8185,9156,9227,9263,9455],[1.5843655610685339,3.4794445051588205,5.335796419868605,2.0059520203103314,0.6357214823748142,4.8678981113821465,5.394427775031819,3.669914566006276,3.3278777562703863,3.7533812701633815,7.293720367315988,3.9376016234782525,3.873416196750468,3.9614366693216145,4.780751644895519])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|4.0  |(10000,[221,222,234,447,494,671,1634,2080,2568,2577,2616,2630,2913,3092,3372,3494,3496,3644,3691,3792,4689,4792,4835,5133,6100,6240,6361,6406,6735,7510,7716,7827,8166,8669,8790,8897,9121,9461],[5.789879144479481,3.174538341481538,8.833152838156257,4.753096683205602,7.797237368864982,6.517584013965061,4.257815401985723,4.214295933244349,5.737601280591763,6.834281201508819,3.828847108424541,4.030686847742069,2.8115874802012564,2.4975205428514764,3.3375377824677743,6.526058640956033,4.020793267652879,7.842225013246188,4.766002114969457,2.457189503552027,8.489136593633711,3.8471767746024974,5.862420618479853,1.5486599203672216,5.572731795377436,1.6171027030442424,10.999983250758486,2.6194117631670353,5.722245892508568,3.159692565630258,6.621226986847632,8.43986554462693,3.653095215847555,6.818955231030592,2.5523202446111655,4.003114010263801,5.689763336549264,12.66397213525312])                                                                                                                                                                                                                                                                                           |
|0.0  |(10000,[504,640,2116,3372,3506,4099,4153,4168,4790,5085,6168,6240,6764,7201],[5.592053401149561,6.7281487830724105,3.8131032323956067,0.15893037059370355,2.8249843435785884,2.6130999032491555,6.704133906868537,10.37838589135346,4.404264362046974,6.155718625603637,1.5999568163865172,3.234205406088485,3.7937195297978428,10.006800048254632])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|0.0  |(10000,[750,855,2840,2913,3370,3372,3506,4116,4232,4299,5189,5428,6168,8004,8889],[1.2691988136336083,3.5827401100860827,4.190272004828508,2.8115874802012564,2.0293744171250947,0.7946518529685177,2.8249843435785884,2.7659476881999847,3.1931957862403015,7.273115450791602,6.385988389652889,5.945389443822778,1.5999568163865172,8.014666370464942,3.818481364904019])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+-----+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 5 rows

In [6]:
print("Total Records:", processed_df.count())

Total Records: 481304

In [7]:
train_df, test_df = processed_df.randomSplit(
    [0.8, 0.2],
    seed=SEED
)

print("Training Rows:", train_df.count())
print("Testing Rows :", test_df.count())

Training Rows: 384943
Testing Rows : 96361

In [8]:
import time

from pyspark.ml.classification import (
    LogisticRegression,
    LinearSVC,
    NaiveBayes,
    RandomForestClassifier
)

from pyspark.ml.tuning import (
    ParamGridBuilder,
    CrossValidator
)

from pyspark.ml.evaluation import (
    MulticlassClassificationEvaluator
)

In [9]:
accuracy_eval = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
)

precision_eval = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="weightedPrecision"
)

recall_eval = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="weightedRecall"
)

f1_eval = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="f1"
)

In [10]:
results = []

## **Logistic Regression with CrossValidator**

In [11]:
# ---------------------------------------------------------
# Step 1: Create Logistic Regression Model
# ---------------------------------------------------------

from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    predictionCol="prediction",
    maxIter=20
)

print("Logistic Regression model created successfully.")

Logistic Regression model created successfully.

In [12]:
# ---------------------------------------------------------
# Step 2: Display Model Parameters
# ---------------------------------------------------------

print(lr.explainParams())

aggregationDepth: suggested depth for treeAggregate (>= 2). (default: 2)
elasticNetParam: the ElasticNet mixing parameter, in range [0, 1]. For alpha = 0, the penalty is an L2 penalty. For alpha = 1, it is an L1 penalty. (default: 0.0)
family: The name of family which is a description of the label distribution to be used in the model. Supported options: auto, binomial, multinomial (default: auto)
featuresCol: features column name. (default: features, current: features)
fitIntercept: whether to fit an intercept term. (default: True)
labelCol: label column name. (default: label, current: label)
lowerBoundsOnCoefficients: The lower bounds on coefficients if fitting under bound constrained optimization. The bound matrix must be compatible with the shape (1, number of features) for binomial regression, or (number of classes, number of features) for multinomial regression. (undefined)
lowerBoundsOnIntercepts: The lower bounds on intercepts if fitting under bound constrained optimization. The bounds vector size must beequal with 1 for binomial regression, or the number oflasses for multinomial regression. (undefined)
maxBlockSizeInMB: maximum memory in MB for stacking input data into blocks. Data is stacked within partitions. If more than remaining data size in a partition then it is adjusted to the data size. Default 0.0 represents choosing optimal value, depends on specific algorithm. Must be >= 0. (default: 0.0)
maxIter: max number of iterations (>= 0). (default: 100, current: 20)
predictionCol: prediction column name. (default: prediction, current: prediction)
probabilityCol: Column name for predicted class conditional probabilities. Note: Not all models output well-calibrated probability estimates! These probabilities should be treated as confidences, not precise probabilities. (default: probability)
rawPredictionCol: raw prediction (a.k.a. confidence) column name. (default: rawPrediction)
regParam: regularization parameter (>= 0). (default: 0.0)
standardization: whether to standardize the training features before fitting the model. (default: True)
threshold: Threshold in binary classification prediction, in range [0, 1]. If threshold and thresholds are both set, they must match.e.g. if threshold is p, then thresholds must be equal to [1-p, p]. (default: 0.5)
thresholds: Thresholds in multi-class classification to adjust the probability of predicting each class. Array must have length equal to the number of classes, with values > 0, excepting that at most one value may be 0. The class with largest value p/t is predicted, where p is the original probability of that class and t is the class's threshold. (undefined)
tol: the convergence tolerance for iterative algorithms (>= 0). (default: 1e-06)
upperBoundsOnCoefficients: The upper bounds on coefficients if fitting under bound constrained optimization. The bound matrix must be compatible with the shape (1, number of features) for binomial regression, or (number of classes, number of features) for multinomial regression. (undefined)
upperBoundsOnIntercepts: The upper bounds on intercepts if fitting under bound constrained optimization. The bound vector size must be equal with 1 for binomial regression, or the number of classes for multinomial regression. (undefined)
weightCol: weight column name. If this is not set or empty, we treat all instance weights as 1.0. (undefined)

In [13]:
# ---------------------------------------------------------
# Step 3: Hyperparameter Grid (Reduced for Memory Safety)
# ---------------------------------------------------------
from pyspark.ml.tuning import ParamGridBuilder

lr_paramGrid = (
    ParamGridBuilder()
    .addGrid(lr.regParam, [0.01])
    .addGrid(lr.elasticNetParam, [0.0, 0.5])
    .build()
)

print("Total Parameter Combinations:", len(lr_paramGrid))

Total Parameter Combinations: 2

In [14]:
# ---------------------------------------------------------
# Step 4: Cross Validation (Reduced numFolds to avoid OOM)
# ---------------------------------------------------------
from pyspark.ml.tuning import CrossValidator

lr_cv = CrossValidator(
    estimator=lr,
    estimatorParamMaps=lr_paramGrid,
    evaluator=accuracy_eval,
    numFolds=2,  # Reduced from 3 to 2
    seed=SEED
)

In [15]:
# ---------------------------------------------------------
# Step 5: Start Timer
# ---------------------------------------------------------

import time

lr_start = time.time()

In [16]:
# ---------------------------------------------------------
# Step 6: Train Logistic Regression with Sampling (Memory Safety)
# ---------------------------------------------------------

try:
    # Since the full dataset (385k) causes OOM in CrossValidation,
    # we will take a representative sample of 50k records for training.
    train_sample = train_df.sample(withReplacement=False, fraction=50000/384943, seed=SEED)

    print(f"Training on a sample of {train_sample.count()} records for memory safety...")

    # Fit the model using the sample
    lr_cv_model = lr_cv.fit(train_sample)
    print("Training completed successfully!")

except Exception as e:
    print(f"Training failed. Please ensure you restarted the runtime after the last crash. Error: {e}")

Training on a sample of 50110 records for memory safety...
Training completed successfully!

In [17]:


lr_end = time.time()

lr_training_time = lr_end - lr_start

print(f"Training Time: {lr_training_time:.2f} seconds")

Training Time: 120.14 seconds

In [18]:
# ---------------------------------------------------------
# Step 8: Extract Best Model
# ---------------------------------------------------------

if 'lr_cv_model' in globals():
    best_lr = lr_cv_model.bestModel
    print("Best Model extracted successfully.")
    print(best_lr.explainParams())
else:
    print("Error: lr_cv_model is not defined. Please ensure Step 6 (training) completes successfully without OOM errors.")

Best Model extracted successfully.
aggregationDepth: suggested depth for treeAggregate (>= 2). (default: 2)
elasticNetParam: the ElasticNet mixing parameter, in range [0, 1]. For alpha = 0, the penalty is an L2 penalty. For alpha = 1, it is an L1 penalty. (default: 0.0, current: 0.5)
family: The name of family which is a description of the label distribution to be used in the model. Supported options: auto, binomial, multinomial (default: auto)
featuresCol: features column name. (default: features, current: features)
fitIntercept: whether to fit an intercept term. (default: True)
labelCol: label column name. (default: label, current: label)
lowerBoundsOnCoefficients: The lower bounds on coefficients if fitting under bound constrained optimization. The bound matrix must be compatible with the shape (1, number of features) for binomial regression, or (number of classes, number of features) for multinomial regression. (undefined)
lowerBoundsOnIntercepts: The lower bounds on intercepts if fitting under bound constrained optimization. The bounds vector size must beequal with 1 for binomial regression, or the number oflasses for multinomial regression. (undefined)
maxBlockSizeInMB: maximum memory in MB for stacking input data into blocks. Data is stacked within partitions. If more than remaining data size in a partition then it is adjusted to the data size. Default 0.0 represents choosing optimal value, depends on specific algorithm. Must be >= 0. (default: 0.0)
maxIter: max number of iterations (>= 0). (default: 100, current: 20)
predictionCol: prediction column name. (default: prediction, current: prediction)
probabilityCol: Column name for predicted class conditional probabilities. Note: Not all models output well-calibrated probability estimates! These probabilities should be treated as confidences, not precise probabilities. (default: probability)
rawPredictionCol: raw prediction (a.k.a. confidence) column name. (default: rawPrediction)
regParam: regularization parameter (>= 0). (default: 0.0, current: 0.01)
standardization: whether to standardize the training features before fitting the model. (default: True)
threshold: Threshold in binary classification prediction, in range [0, 1]. If threshold and thresholds are both set, they must match.e.g. if threshold is p, then thresholds must be equal to [1-p, p]. (default: 0.5)
thresholds: Thresholds in multi-class classification to adjust the probability of predicting each class. Array must have length equal to the number of classes, with values > 0, excepting that at most one value may be 0. The class with largest value p/t is predicted, where p is the original probability of that class and t is the class's threshold. (undefined)
tol: the convergence tolerance for iterative algorithms (>= 0). (default: 1e-06)
upperBoundsOnCoefficients: The upper bounds on coefficients if fitting under bound constrained optimization. The bound matrix must be compatible with the shape (1, number of features) for binomial regression, or (number of classes, number of features) for multinomial regression. (undefined)
upperBoundsOnIntercepts: The upper bounds on intercepts if fitting under bound constrained optimization. The bound vector size must be equal with 1 for binomial regression, or the number of classes for multinomial regression. (undefined)
weightCol: weight column name. If this is not set or empty, we treat all instance weights as 1.0. (undefined)

In [19]:
lr_predictions = lr_cv_model.transform(test_df)

In [20]:
lr_predictions.select(

    "label",

    "prediction",

    "probability"

).show(10, truncate=False)

+-----+----------+-----------------------------------------------------------------------------------------------------+
|label|prediction|probability                                                                                          |
+-----+----------+-----------------------------------------------------------------------------------------------------+
|3.0  |0.0       |[0.5750282200369988,0.13520030083758183,0.10061531162122828,0.12062037026121183,0.06853579724297933] |
|3.0  |3.0       |[0.06675466425156408,0.1101735269035033,0.12324143749194903,0.6023645796585633,0.0974657916944201]   |
|3.0  |3.0       |[0.10204435893411248,0.04996216667628567,0.046788293458975,0.754651568084988,0.046553612845638706]   |
|3.0  |0.0       |[0.3226352045486764,0.16003158235931184,0.12217440181438058,0.3209612349338819,0.07419757634374936]  |
|3.0  |0.0       |[0.5929586284780003,0.18930173717920057,0.08246333871989557,0.08864315328114994,0.04663314234175351] |
|3.0  |0.0       |[0.45843125452136296,0.08996250720503034,0.0995682513914917,0.2660059697956642,0.08603201708645085]  |
|3.0  |0.0       |[0.37769895140959237,0.15402383193849198,0.15220086061440732,0.21396218921987856,0.10211416681762979]|
|3.0  |0.0       |[0.40680210526875754,0.30999161986037743,0.12538623580881433,0.0769422311806617,0.08087780788138885] |
|3.0  |3.0       |[0.10254410576212987,0.31430208061415754,0.14960111829655398,0.3145618049383342,0.11899089038882442] |
|3.0  |3.0       |[0.12871897760074605,0.09610292052185673,0.13704851031487938,0.49965015381093003,0.138479437751588]  |
+-----+----------+-----------------------------------------------------------------------------------------------------+
only showing top 10 rows

In [21]:
lr_predictions.printSchema()

root
 |-- rating: double (nullable = true)
 |-- text: string (nullable = true)
 |-- title: string (nullable = true)
 |-- review: string (nullable = true)
 |-- label: double (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- filtered_words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- rawFeatures: vector (nullable = true)
 |-- features: vector (nullable = true)
 |-- rawPrediction: vector (nullable = true)
 |-- probability: vector (nullable = true)
 |-- prediction: double (nullable = false)

In [22]:
print("Prediction Records:", lr_predictions.count())

Prediction Records: 96361

In [23]:
lr_predictions.groupBy("prediction").count().show()

+----------+-----+
|prediction|count|
+----------+-----+
|       1.0| 6083|
|       4.0|  287|
|       0.0|82370|
|       3.0| 4551|
|       2.0| 3070|
+----------+-----+

In [24]:
lr_predictions.cache()

lr_predictions.count()

print("Prediction dataset cached successfully.")

Prediction dataset cached successfully.

In [29]:
# Calculate all metrics including the missing F1 score
lr_accuracy = accuracy_eval.evaluate(lr_predictions)
lr_f1 = f1_eval.evaluate(lr_predictions)

print(f"Accuracy  : {lr_accuracy:.4f}")
print(f"Precision : {lr_precision:.4f}")
print(f"Recall    : {lr_recall:.4f}")
print(f"F1 Score  : {lr_f1:.4f}")

Accuracy  : 0.6964
Precision : 0.6504
Recall    : 0.6964
F1 Score  : 0.6342

## **Logistic Regression Performance**

In [30]:


print("=" * 60)
print("LOGISTIC REGRESSION PERFORMANCE")
print("=" * 60)

print(f"Accuracy      : {lr_accuracy:.4f}")
print(f"Precision     : {lr_precision:.4f}")
print(f"Recall        : {lr_recall:.4f}")
print(f"F1 Score      : {lr_f1:.4f}")
print(f"Training Time : {lr_training_time:.2f} seconds")

print("=" * 60)

============================================================
LOGISTIC REGRESSION PERFORMANCE
============================================================
Accuracy      : 0.6964
Precision     : 0.6504
Recall        : 0.6964
F1 Score      : 0.6342
Training Time : 120.14 seconds
============================================================

# **Display Best Hyperparameters**

In [31]:

best_lr = lr_cv_model.bestModel

print("Best Logistic Regression Parameters")

print("-----------------------------------")

print("Max Iterations :", best_lr.getMaxIter())

print("Regularization Parameter :", best_lr.getRegParam())

print("ElasticNet Parameter :", best_lr.getElasticNetParam())

Best Logistic Regression Parameters
-----------------------------------
Max Iterations : 20
Regularization Parameter : 0.01
ElasticNet Parameter : 0.5

In [32]:
best_lr.write() \
    .overwrite() \
    .save("/content/drive/MyDrive/7006SCN/LR_Model")

print("Logistic Regression model saved successfully.")

Logistic Regression model saved successfully.

In [33]:
results.append({

    "Model": "Logistic Regression",

    "Accuracy": lr_accuracy,

    "Precision": lr_precision,

    "Recall": lr_recall,

    "F1 Score": lr_f1,

    "Training Time (Seconds)": lr_training_time

})

print("Results added successfully.")

Results added successfully.

In [34]:
print(results)

[{'Model': 'Logistic Regression', 'Accuracy': 0.6963605608077957, 'Precision': 0.6504381340007208, 'Recall': 0.6963605608077957, 'F1 Score': 0.634235332816163, 'Training Time (Seconds)': 120.14390850067139}]

In [35]:
import pandas as pd

pd.DataFrame(results)

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds)
0,Logistic Regression,0.696361,0.650438,0.696361,0.634235,120.143909

In [36]:

lr_predictions.select(
    "label",
    "prediction",
    "probability"
).show(10, truncate=False)

+-----+----------+-----------------------------------------------------------------------------------------------------+
|label|prediction|probability                                                                                          |
+-----+----------+-----------------------------------------------------------------------------------------------------+
|3.0  |0.0       |[0.5750282200369988,0.13520030083758183,0.10061531162122828,0.12062037026121183,0.06853579724297933] |
|3.0  |3.0       |[0.06675466425156408,0.1101735269035033,0.12324143749194903,0.6023645796585633,0.0974657916944201]   |
|3.0  |3.0       |[0.10204435893411248,0.04996216667628567,0.046788293458975,0.754651568084988,0.046553612845638706]   |
|3.0  |0.0       |[0.3226352045486764,0.16003158235931184,0.12217440181438058,0.3209612349338819,0.07419757634374936]  |
|3.0  |0.0       |[0.5929586284780003,0.18930173717920057,0.08246333871989557,0.08864315328114994,0.04663314234175351] |
|3.0  |0.0       |[0.45843125452136296,0.08996250720503034,0.0995682513914917,0.2660059697956642,0.08603201708645085]  |
|3.0  |0.0       |[0.37769895140959237,0.15402383193849198,0.15220086061440732,0.21396218921987856,0.10211416681762979]|
|3.0  |0.0       |[0.40680210526875754,0.30999161986037743,0.12538623580881433,0.0769422311806617,0.08087780788138885] |
|3.0  |3.0       |[0.10254410576212987,0.31430208061415754,0.14960111829655398,0.3145618049383342,0.11899089038882442] |
|3.0  |3.0       |[0.12871897760074605,0.09610292052185673,0.13704851031487938,0.49965015381093003,0.138479437751588]  |
+-----+----------+-----------------------------------------------------------------------------------------------------+
only showing top 10 rows

In [37]:
lr_predictions.groupBy("prediction").count().show()

+----------+-----+
|prediction|count|
+----------+-----+
|       1.0| 6083|
|       4.0|  287|
|       0.0|82370|
|       3.0| 4551|
|       2.0| 3070|
+----------+-----+

In [38]:
correct_predictions = lr_predictions.filter(
    lr_predictions.label == lr_predictions.prediction
).count()

print("Correct Predictions:", correct_predictions)

Correct Predictions: 67102

In [39]:
incorrect_predictions = lr_predictions.filter(
    lr_predictions.label != lr_predictions.prediction
).count()

print("Incorrect Predictions:", incorrect_predictions)

Incorrect Predictions: 29259

In [40]:
print("=" * 60)
print("LOGISTIC REGRESSION MODEL COMPLETED SUCCESSFULLY")
print("=" * 60)

============================================================
LOGISTIC REGRESSION MODEL COMPLETED SUCCESSFULLY
============================================================

## **Reusable Model Training & Evaluation Function**
This function automates the training (with sampling), cross-validation, performance metrics calculation, and model saving for any Spark ML classifier.

In [44]:
def train_and_evaluate(model, param_grid, model_name, save_path):
    print(f"\n{'='*60}")
    print(f"STARTING: {model_name}")
    print(f"{'='*60}")

    start_time = time.time()

    try:
        # Step 1: Initialize CrossValidator
        cv = CrossValidator(
            estimator=model,
            estimatorParamMaps=param_grid,
            evaluator=accuracy_eval,
            numFolds=2,
            seed=SEED
        )

        # Step 2: Dynamic Sampling for Memory Safety
        train_count = train_df.count()
        sample_fraction = min(50000 / train_count, 1.0)
        train_sample = train_df.sample(withReplacement=False, fraction=sample_fraction, seed=SEED)
        print(f"Training {model_name} on {train_sample.count()} records (Sample fraction: {sample_fraction:.4f})...")

        # Step 3: Train Model
        cv_model = cv.fit(train_sample)
        end_time = time.time()
        duration = end_time - start_time
        print(f"Training completed in {duration:.2f} seconds.")

        # Step 4: Predictions and Evaluation
        predictions = cv_model.transform(test_df)

        acc = accuracy_eval.evaluate(predictions)
        prec = precision_eval.evaluate(predictions)
        rec = recall_eval.evaluate(predictions)
        f1 = f1_eval.evaluate(predictions)

        # Step 5: Save Best Model and CV Model
        best_model = cv_model.bestModel
        best_model.write().overwrite().save(save_path)
        cv_model.write().overwrite().save(save_path + "_CV")
        print(f"Models saved successfully to {save_path}")

        # Step 6: Store Results with Best Parameters
        results.append({
            "Model": model_name,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1 Score": f1,
            "Training Time (Seconds)": duration,
            "Best Parameters": str(best_model.extractParamMap())
        })

        # Step 7: Print Performance Summary
        print(f"\n{model_name} Results:")
        print(f"- Accuracy  : {acc:.4f}")
        print(f"- Precision : {prec:.4f}")
        print(f"- Recall    : {rec:.4f}")
        print(f"- F1 Score  : {f1:.4f}")

        return cv_model

    except Exception as e:
        print(f"Error training {model_name}: {e}")
        return None

###  Linear Support Vector Machine (LinearSVC)

In [45]:
from pyspark.ml.classification import LinearSVC, OneVsRest

# Define the base Binary Model
lsvc = LinearSVC(featuresCol="features", labelCol="label", maxIter=10)

# Wrap it in OneVsRest for multi-class support
ovr = OneVsRest(classifier=lsvc, labelCol="label", featuresCol="features")

# Define ParamGrid
lsvc_paramGrid = (ParamGridBuilder()
                  .addGrid(lsvc.regParam, [0.01, 0.1])
                  .build())

# Run training
lsvc_model = train_and_evaluate(
    model=ovr,
    param_grid=lsvc_paramGrid,
    model_name="Linear SVM (OneVsRest)",
    save_path="/content/drive/MyDrive/7006SCN/LSVC_Model"
)

============================================================
STARTING: Linear SVM (OneVsRest)
============================================================
Training Linear SVM (OneVsRest) on 50110 records (Sample fraction: 0.1299)...
Training completed in 148.09 seconds.
Models saved successfully to /content/drive/MyDrive/7006SCN/LSVC_Model

Linear SVM (OneVsRest) Results:
- Accuracy  : 0.6994
- Precision : 0.6513
- Recall    : 0.6994
- F1 Score  : 0.6638

In [46]:
from pyspark.ml.classification import NaiveBayes

nb = NaiveBayes(featuresCol="features", labelCol="label")

nb_paramGrid = (ParamGridBuilder()
                .addGrid(nb.smoothing, [0.5, 1.0])
                .build())

nb_model = train_and_evaluate(
    model=nb,
    param_grid=nb_paramGrid,
    model_name="Naive Bayes",
    save_path="/content/drive/MyDrive/7006SCN/NB_Model"
)

============================================================
STARTING: Naive Bayes
============================================================
Training Naive Bayes on 50110 records (Sample fraction: 0.1299)...
Training completed in 74.60 seconds.
Models saved successfully to /content/drive/MyDrive/7006SCN/NB_Model

Naive Bayes Results:
- Accuracy  : 0.6248
- Precision : 0.6659
- Recall    : 0.6248
- F1 Score  : 0.6419

### ** Random Forest Classifier**
Training the final model using our optimized helper function.

In [52]:
from pyspark.ml.classification import RandomForestClassifier

# Define Model
rf = RandomForestClassifier(featuresCol="features", labelCol="label", seed=SEED)

# Define ParamGrid
rf_paramGrid = (ParamGridBuilder()
                .addGrid(rf.numTrees, [20, 50])
                .addGrid(rf.maxDepth, [5, 10])
                .build())

# Run training and evaluation
rf_model = train_and_evaluate(
    model=rf,
    param_grid=rf_paramGrid,
    model_name="Random Forest",
    save_path="/content/drive/MyDrive/7006SCN/RF_Model"
)

============================================================
STARTING: Random Forest
============================================================
Training Random Forest on 50110 records (Sample fraction: 0.1299)...
Training completed in 347.95 seconds.
Models saved successfully to /content/drive/MyDrive/7006SCN/RF_Model

Random Forest Results:
- Accuracy  : 0.6320
- Precision : 0.3994
- Recall    : 0.6320
- F1 Score  : 0.4895

## **Final Model Comparison Summary**

In [53]:
import pandas as pd

# Create final comparison table
comparison_df = pd.DataFrame(results).round(4)

# Sort by Accuracy
comparison_df = comparison_df.sort_values(by="Accuracy", ascending=False)

# Save to Drive
comparison_df.to_csv("/content/drive/MyDrive/7006SCN/model_comparison_final.csv", index=False)

print("Final Comparison Table saved to Drive.")
comparison_df

Final Comparison Table saved to Drive.

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds),Best Parameters
1,Linear SVM (OneVsRest),0.6994,0.6513,0.6994,0.6638,148.0854,"{Param(parent='OneVsRestModel_f8dba0c5e9b7', n..."
0,Logistic Regression,0.6964,0.6504,0.6964,0.6342,120.1439,NaN
3,Random Forest,0.6320,0.3994,0.6320,0.4895,347.9453,{Param(parent='RandomForestClassifier_03fc4391...
2,Naive Bayes,0.6248,0.6659,0.6248,0.6419,74.6033,"{Param(parent='NaiveBayes_5cbc5bbfe07d', name=..."

In [54]:
import pandas as pd

comparison_df = pd.DataFrame(results)

comparison_df

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds),Best Parameters
0,Logistic Regression,0.696361,0.650438,0.696361,0.634235,120.143909,NaN
1,Linear SVM (OneVsRest),0.699360,0.651270,0.699360,0.663795,148.085375,"{Param(parent='OneVsRestModel_f8dba0c5e9b7', n..."
2,Naive Bayes,0.624755,0.665942,0.624755,0.641872,74.603323,"{Param(parent='NaiveBayes_5cbc5bbfe07d', name=..."
3,Random Forest,0.631978,0.399396,0.631978,0.489462,347.945322,{Param(parent='RandomForestClassifier_03fc4391...

In [55]:
comparison_df = comparison_df.round(4)

comparison_df

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds),Best Parameters
0,Logistic Regression,0.6964,0.6504,0.6964,0.6342,120.1439,NaN
1,Linear SVM (OneVsRest),0.6994,0.6513,0.6994,0.6638,148.0854,"{Param(parent='OneVsRestModel_f8dba0c5e9b7', n..."
2,Naive Bayes,0.6248,0.6659,0.6248,0.6419,74.6033,"{Param(parent='NaiveBayes_5cbc5bbfe07d', name=..."
3,Random Forest,0.6320,0.3994,0.6320,0.4895,347.9453,{Param(parent='RandomForestClassifier_03fc4391...

In [56]:
print("=" * 100)
print("MODEL COMPARISON SUMMARY")
print("=" * 100)

print(comparison_df)

====================================================================================================
MODEL COMPARISON SUMMARY
====================================================================================================
                    Model  Accuracy  Precision  Recall  F1 Score  \
0     Logistic Regression    0.6964     0.6504  0.6964    0.6342
1  Linear SVM (OneVsRest)    0.6994     0.6513  0.6994    0.6638
2             Naive Bayes    0.6248     0.6659  0.6248    0.6419
3           Random Forest    0.6320     0.3994  0.6320    0.4895

   Training Time (Seconds)                                    Best Parameters
0                 120.1439                                                NaN
1                 148.0854  {Param(parent='OneVsRestModel_f8dba0c5e9b7', n...
2                  74.6033  {Param(parent='NaiveBayes_5cbc5bbfe07d', name=...
3                 347.9453  {Param(parent='RandomForestClassifier_03fc4391...

In [57]:
comparison_df = comparison_df.sort_values(
    by="Accuracy",
    ascending=False
)

comparison_df

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds),Best Parameters
1,Linear SVM (OneVsRest),0.6994,0.6513,0.6994,0.6638,148.0854,"{Param(parent='OneVsRestModel_f8dba0c5e9b7', n..."
0,Logistic Regression,0.6964,0.6504,0.6964,0.6342,120.1439,NaN
3,Random Forest,0.6320,0.3994,0.6320,0.4895,347.9453,{Param(parent='RandomForestClassifier_03fc4391...
2,Naive Bayes,0.6248,0.6659,0.6248,0.6419,74.6033,"{Param(parent='NaiveBayes_5cbc5bbfe07d', name=..."

In [58]:
best_model = comparison_df.iloc[0]

print("Best Model")

print(best_model)

Best Model
Model                                                 Linear SVM (OneVsRest)
Accuracy                                                              0.6994
Precision                                                             0.6513
Recall                                                                0.6994
F1 Score                                                              0.6638
Training Time (Seconds)                                             148.0854
Best Parameters            {Param(parent='OneVsRestModel_f8dba0c5e9b7', n...
Name: 1, dtype: object

In [58]:
comparison_df.to_csv(
    "/content/drive/MyDrive/7006SCN/model_comparison.csv",
    index=False
)

print("Comparison table saved.")

In [59]:
comparison_df.head()

,Model,Accuracy,Precision,Recall,F1 Score,Training Time (Seconds),Best Parameters
1,Linear SVM (OneVsRest),0.6994,0.6513,0.6994,0.6638,148.0854,"{Param(parent='OneVsRestModel_f8dba0c5e9b7', n..."
0,Logistic Regression,0.6964,0.6504,0.6964,0.6342,120.1439,NaN
3,Random Forest,0.6320,0.3994,0.6320,0.4895,347.9453,{Param(parent='RandomForestClassifier_03fc4391...
2,Naive Bayes,0.6248,0.6659,0.6248,0.6419,74.6033,"{Param(parent='NaiveBayes_5cbc5bbfe07d', name=..."

In [61]:
import os

files = os.listdir("/content/drive/MyDrive/7006SCN")

for file in files:
    print(file)

Pipeline_Task2
processed_reviews
LR_Model
LSVC_Model
LSVC_Model_CV
NB_Model
NB_Model_CV
RF_Model
RF_Model_CV
model_comparison_final.csv

In [62]:
print("=" * 80)
print("TASK 3 COMPLETED SUCCESSFULLY")
print("=" * 80)

print("Models Trained")

print("1. Logistic Regression")

print("2. Linear SVM")

print("3. Naive Bayes")

print("4. Random Forest")

print()

print("Comparison table created")

print("Models saved")

print("Results exported")

================================================================================
TASK 3 COMPLETED SUCCESSFULLY
================================================================================
Models Trained
1. Logistic Regression
2. Linear SVM
3. Naive Bayes
4. Random Forest

Comparison table created
Models saved
Results exported