# **●	Task1 — Problem & Dataset**

In [1]:
# Install required libraries
!pip install -q pyspark datasets pyarrow pandas

In [2]:
from datasets import load_dataset
from pyspark.sql import SparkSession
import pandas as pd
import os

In [3]:
spark = (
    SparkSession.builder
    .appName("Amazon Beauty Reviews Analysis")
    .getOrCreate()
)

print("Spark Version:", spark.version)

Spark Version: 4.0.3

In [5]:
# Load the Beauty & Personal Care category

dataset = load_dataset(
    "bagadbilla/amazon-reviews-2023-trimmed",
    data_dir="Beauty_and_Personal_Care",
    split="train"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/95 [00:00<?, ?it/s]

In [6]:
# 1. Save the full dataset in Hugging Face format (efficient)
dataset.save_to_disk('amazon_beauty_reviews_arrow')

# 2. Save a sample to CSV for portability
sample_to_save = dataset.select(range(10000))
sample_to_save.to_csv('amazon_beauty_sample.csv')

print("Dataset saved successfully!")

Saving the dataset (0/11 shards):   0%|          | 0/23911390 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/10 [00:00<?, ?ba/s]

Dataset saved successfully!

In [7]:
print(dataset)

Dataset({
    features: ['rating', 'title', 'text'],
    num_rows: 23911390
})

In [8]:
print("Total Records:", len(dataset))

Total Records: 23911390

In [9]:
print(dataset.features)

{'rating': Value('float64'), 'title': Value('string'), 'text': Value('string')}

In [10]:
dataset[0]

{'rating': 1.0,
 'title': 'Gasoline!! Seriously reeks of gasoline!',
 'text': 'Opened the package & instant migraine. I cannot believe the stench.  I have purchased other packages that did not smell at all so I do not know if these were a damaged shipment or damaged during packaging or what, but the minute I opened the Amazon package I smelled it before I even opened the Terra Tattoos package. I couldn’t believe it. Then I find that the pink inks from the back have smeared all over the fronts of the tattoos. Yes, you eventually take the clear part off to apply the tattoo, but I always lay it down with the clear covering first to line it up & I didn’t want to risk the pink ink transferring to my art projects so it’s going back. I’ll update the review when Amazon sends my replacement. I’m upset because now my resin is here & I don’t have the tattoos to do my project, but I’m more mad about the fact that I have a massive migraine because of the gasoline fumes that lingered.  I believe they arrived a week ago, but I didn’t check the tattoos then as I didn’t have resin & the smell of gasoline is just as string toast when I opened them to check them as it was last week when I forgot to start the return. I’ve been sick or I would have done it already.  I really hope the replacement tattoos are okay.'}

In [11]:
sample = dataset.select(range(1000))

pdf = sample.to_pandas()

pdf.head()

,rating,title,text
0,1.0,Gasoline!! Seriously reeks of gasoline!,Opened the package & instant migraine. I canno...
1,1.0,Useless! These have massive gaps at pump nozzle.,Tops the list for worst purchase. Tried these ...
2,5.0,Hailey loves unicorns!,Bought this for my granddaughter. Her entire ...
3,1.0,Not sharp enough to cut smoothly.,These are extremely dull and will wreck your n...
4,3.0,"Pretty, but didn’t close correctly.",Mine wouldn’t close correctly so I sent it bac...

In [12]:
print(pdf.columns.tolist())

['rating', 'title', 'text']

In [13]:
pdf.dtypes

rating    float64
title      object
text       object
dtype: object

In [14]:
pdf.isnull().sum()

rating    0
title     0
text      0
dtype: int64

In [16]:
# Create a Spark DataFrame from a smaller sample (e.g., first 1000 records)
spark_df_sample = spark.createDataFrame(dataset.select(range(1000)))
spark_df_sample.printSchema()
spark_df_sample.show(5, truncate=False)
print("Total Rows in Sample Spark DataFrame:", spark_df_sample.count())

root
 |-- rating: double (nullable = true)
 |-- text: string (nullable = true)
 |-- title: string (nullable = true)

+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
|rating|text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |title                                            |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
|1.0   |Opened the package & instant migraine. I cannot believe the stench.  I have purchased other packages that did not smell at all so I do not know if these were a damaged shipment or damaged during packaging or what, but the minute I opened the Amazon package I smelled it before I even opened the Terra Tattoos package. I couldn’t believe it. Then I find that the pink inks from the back have smeared all over the fronts of the tattoos. Yes, you eventually take the clear part off to apply the tattoo, but I always lay it down with the clear covering first to line it up & I didn’t want to risk the pink ink transferring to my art projects so it’s going back. I’ll update the review when Amazon sends my replacement. I’m upset because now my resin is here & I don’t have the tattoos to do my project, but I’m more mad about the fact that I have a massive migraine because of the gasoline fumes that lingered.  I believe they arrived a week ago, but I didn’t check the tattoos then as I didn’t have resin & the smell of gasoline is just as string toast when I opened them to check them as it was last week when I forgot to start the return. I’ve been sick or I would have done it already.  I really hope the replacement tattoos are okay.|Gasoline!! Seriously reeks of gasoline!          |
|1.0   |Tops the list for worst purchase. Tried these for alcohol inks.  Half won’t spray. My mistake was not checking that every bottle would spray before filling them. I only checked 2. They both sprayed so I proceeded. What a nightmare. There is a gap where the pump is so if you shake your ink up and down it literally comes out the top which is why these are such a mess and if you knock it over the ink escapes.  Luckily I worked over my sink or the mess would have been worse, but I’m still wearing  a lot of ink days later.  These were a debacle start to finish.  I should have checked the bottles better before putting my ink in. 1/4 work okay, but will still spill ink if knocked over or shaken. 1/4 spray, but the spray is like a diagonal slash pattern not a nice round spray pattern  1/2 won’t spray at all.  Literally worst amazon purchase ever & now my inks are trapped in an item I need to return!!!  Ugh.                                                                                                                                                                                                                                                                                                                                  |Useless!  These have massive gaps at pump nozzle.|
|5.0   |Bought this for my granddaughter.  Her entire family including her 4 siblings & mom & dad love doing these.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |Hailey loves unicorns!                           |
|1.0   |These are extremely dull and will wreck your nails. They were not sharpened apparently.  It’s a complete waste of money, but luckily Amazon refunded me.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |Not sharp enough to cut smoothly.                |
|3.0   |Mine wouldn’t close correctly so I sent it back. It’s pretty and useful, but expect it to close properly.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |Pretty, but didn’t close correctly.              |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
only showing top 5 rows
Total Rows in Sample Spark DataFrame: 1000

In [18]:
# Trying a slightly larger but manageable sample (100,000 rows)
spark_df = spark.createDataFrame(dataset.select(range(100000)))
print(f"Successfully created Spark DataFrame with {spark_df.count()} rows.")

Successfully created Spark DataFrame with 100000 rows.

In [19]:
spark_df.printSchema()

root
 |-- rating: double (nullable = true)
 |-- text: string (nullable = true)
 |-- title: string (nullable = true)

In [20]:
spark_df.show(20, truncate=False)

+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
|rating|text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |title                                                 |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
|1.0   |Opened the package & instant migraine. I cannot believe the stench.  I have purchased other packages that did not smell at all so I do not know if these were a damaged shipment or damaged during packaging or what, but the minute I opened the Amazon package I smelled it before I even opened the Terra Tattoos package. I couldn’t believe it. Then I find that the pink inks from the back have smeared all over the fronts of the tattoos. Yes, you eventually take the clear part off to apply the tattoo, but I always lay it down with the clear covering first to line it up & I didn’t want to risk the pink ink transferring to my art projects so it’s going back. I’ll update the review when Amazon sends my replacement. I’m upset because now my resin is here & I don’t have the tattoos to do my project, but I’m more mad about the fact that I have a massive migraine because of the gasoline fumes that lingered.  I believe they arrived a week ago, but I didn’t check the tattoos then as I didn’t have resin & the smell of gasoline is just as string toast when I opened them to check them as it was last week when I forgot to start the return. I’ve been sick or I would have done it already.  I really hope the replacement tattoos are okay.|Gasoline!! Seriously reeks of gasoline!               |
|1.0   |Tops the list for worst purchase. Tried these for alcohol inks.  Half won’t spray. My mistake was not checking that every bottle would spray before filling them. I only checked 2. They both sprayed so I proceeded. What a nightmare. There is a gap where the pump is so if you shake your ink up and down it literally comes out the top which is why these are such a mess and if you knock it over the ink escapes.  Luckily I worked over my sink or the mess would have been worse, but I’m still wearing  a lot of ink days later.  These were a debacle start to finish.  I should have checked the bottles better before putting my ink in. 1/4 work okay, but will still spill ink if knocked over or shaken. 1/4 spray, but the spray is like a diagonal slash pattern not a nice round spray pattern  1/2 won’t spray at all.  Literally worst amazon purchase ever & now my inks are trapped in an item I need to return!!!  Ugh.                                                                                                                                                                                                                                                                                                                                  |Useless!  These have massive gaps at pump nozzle.     |
|5.0   |Bought this for my granddaughter.  Her entire family including her 4 siblings & mom & dad love doing these.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |Hailey loves unicorns!                                |
|1.0   |These are extremely dull and will wreck your nails. They were not sharpened apparently.  It’s a complete waste of money, but luckily Amazon refunded me.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |Not sharp enough to cut smoothly.                     |
|3.0   |Mine wouldn’t close correctly so I sent it back. It’s pretty and useful, but expect it to close properly.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |Pretty, but didn’t close correctly.                   |
|1.0   |I don't often leave negative feedback about products - it really has to be a pretty poorly made product for that to happen. Unfortunately, these bottles are super leaky, even with the rollerball tightly secured and the lid properly screwed on. The screw-on lids seem a poor fit for the bottles, and one of them leaked all over a leather purse in which the bottle was being carried, ruining it. (First world problems, I know). I contacted Amazon to see about a refund, but the only way they would refund the purchase is if I returned the bottles - which are filled with essential oil blends, and I would have to dump it all out to send the bottles back, or buy another set of bottles and try to transfer the oil over. For $9 it wasn't worth all that, even with the $5 additional credit they offered, so I had to chalk this up as a loss and a &#34;buyer beware - read the reviews!&#34; So please - read the reviews. I'm not the only one who had this problem! (Also, note the number of people who received a discount or received this product for free in exchange for leaving a review).                                                                                                                                                        |Unbottled disappointment                              |
|1.0   |Based on other reviews, I thought this would be a great product. I was surprised and disappointed to discover that this shade is truly colorless on my lips, and it doesn't possess any noticeable plumping factor. Also, other reviewers mentioned that this burns quite a bit and I totally disagree. There is some level of slight burning but it's very subtle. I've tried other lip plumpers that work much better, such as the Physician's Formula Plump Potion. While very sticky, that particular gloss does do what it's advertised to do. The NYX Pump it Up gloss really isn't worth the money. Anyway, people looking for long-lasting plumping won't really get results from a lip gloss - that usually requires some sort of collagen injection, and I'm not about to go there. I'll just have to be satisfied with my less-than-Angelina pout and chalk it up to genetics. :-)                                                                                                                                                                                                                                                                                                                                                                                     |Not pink, doesn't plump.                              |
|5.0   |This stuff smells amazing.... got it for my man. I really like it                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |Five Stars                                            |
|3.0   |I have used PFB vanish normally and decided to try this set instead. Its OK nothing spectacular. Very heavy alcohol with the tend skin, it does work however but its just OK in my book. I will definitely keep and use but not sure I'd repurchase. The roller/travel item- its nice that it can be refilled but just doesn't work all that well.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |OK                                                    |
|4.0   |Nice set at a reasonable price. I got a few for gifts. I will say the lipstick is a bit grainy/dry but the color is very pretty. I mix it with balm or gloss to wear                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |Neutral set flatters most                             |
|3.0   |These are very cute but they are quite small and the quality of the clips varies quite a bit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |The clips vary...                                     |
|5.0   |Beautiful palette- very pleased! I got one as a gift and one for myself. Great range of both fun and neutral colors. Its a keeper!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |Beautiful palette- very pleased                       |

In [21]:
print("Total Rows:", spark_df.count())

Total Rows: 100000

In [22]:
print("Total Columns:", len(spark_df.columns))

Total Columns: 3

In [23]:
spark_df.dtypes

[('rating', 'double'), ('text', 'string'), ('title', 'string')]

In [24]:
spark_df.describe().show()

+-------+------------------+--------------------+--------------------+
|summary|            rating|                text|               title|
+-------+------------------+--------------------+--------------------+
|  count|            100000|              100000|              100000|
|   mean|           4.25604|                NULL|              3333.0|
| stddev|1.1511545378304797|                NULL|                NULL|
|    min|               1.0|                    |!!YES!! Highly em...|
|    max|               5.0|🤷🏼‍♀️ Smooth “r...|               🧖‍♀️|
+-------+------------------+--------------------+--------------------+

In [25]:
from pyspark.sql.functions import col, sum, when

spark_df.select([
    sum(when(col(c).isNull(), 1).otherwise(0)).alias(c)
    for c in spark_df.columns
]).show()

+------+----+-----+
|rating|text|title|
+------+----+-----+
|     0|   0|    0|
+------+----+-----+

In [26]:
spark_df.groupBy("rating").count().orderBy("rating").show()

+------+-----+
|rating|count|
+------+-----+
|   1.0| 5694|
|   2.0| 4494|
|   3.0| 9087|
|   4.0|19964|
|   5.0|60761|
+------+-----+

In [27]:
print("Partitions:", spark_df.rdd.getNumPartitions())

Partitions: 2

In [28]:
spark_df.cache()

spark_df.count()

100000

In [29]:
import os

dataset_path = dataset.cache_files[0]["filename"]

size_gb = os.path.getsize(dataset_path) / (1024**3)

print(f"Dataset Size: {size_gb:.2f} GB")

Dataset Size: 0.47 GB